### PR TITLE
Read arrow fragment

### PR DESCRIPTION
**Pull request by kingwind94**

### CODE REVIEW

**Comment by JayjeetAtGithub** [comment]
The functions to serialize expressions, schemas, and table to buffer list and back are defined [here](https://github.com/uccross/arrow/blob/rados-dataset/cpp/src/arrow/dataset/rados_utils.h#L63-L82).

The format followed for moving Expression and Schema is 

```
| filter_size (8 bytes) | filter_buffer (filter_size) | schema_size (8 bytes) | schema_buffer (schema_size) | 
```

The format followed for moving Table,

```
| table_buffer (all of the bufferlist) |
```

**Comment by JayjeetAtGithub** [comment]
Hi @jlefevre , I can help with the CLS. I have a few refactorings to be done. I am thinking If I can create a new branch from this branch and work there. I can work there and maybe you can help with some review. Does that sound good ?

**Comment by jlefevre** [comment]
Sure, let me merge that branch into this one and we can continue working from here.

**Comment by JayjeetAtGithub** [comment]
> Sure, let me merge that branch into this one and we can continue working from here.

https://github.com/uccross/skyhookdm-ceph-cls/pull/76

**Comment by jlefevre** [comment]
Hi Jayjeet, I didn't get to this yet but will get to it tomorrow.  Thanks
for all the work on this branch.  I reviewed some of it, and will need to
have a call with you for some quick questions before merging. So how about
8a or 10a Wednesday?  Else maybe 9a Tuesday (tomorrow will work as well).
Jeff

**Comment by JayjeetAtGithub** [comment]
> Hi Jayjeet, I didn't get to this yet but will get to it tomorrow. Thanks for all the work on this branch. I reviewed some of it, and will need to have a call with you for some quick questions before merging. So how about 8a or 10a Wednesday? Else maybe 9a Tuesday (tomorrow will work as well). Jeff

Hi @jlefevre , Thanks for taking a look. 9AM Tuesday or 10 AM Wednesday should be good.

**Pull request closed without merging**
