### PR TITLE
Add logging to compile steps.

### PR DESCRIPTION
**Pull request by jlefevre**

### CODE REVIEW

**Comment by jlefevre** [comment]
This was sometimes failing due to repo issues: 
```
The command '/bin/sh -c yum install -y https://apache.bintray.com/arrow/centos/7/apache-arrow-release-latest.rpm &&     yum install -y       re2-devel       arrow-devel       parquet-devel &&     yum clean all' returned a non-zero code: 1
ERROR: Step 'build-rook-img' failed ('1') !
```

So had to add a `yum update` to this command both in the docker build and docker release files.

**Comment by ivotron** [comment]
> So had to add a `yum update` to this command both in the docker build and docker release files.

looking at the travis log, it looks like a transient network error. `yum install` automatically runs `yum update` when building the container since there's no previously cached package metadata.

**Comment by jlefevre** [comment]
Yes, it seems a transient error, though it happened 2x last night and earlier today as well.  I had restarted the build last night, it failed after waiting ~50 min.  Travis overwrites the build logs on restart so it might not be visible.  So I added the explicit update step, and maybe just got lucky a few times when testing.  It is happening again right now when I build the rook-img locally, so maybe something else going on with the mirrors.  Let's see if it continues then revisit.

**Comment by ivotron** [comment]
yeah, seems to be an issue with the arrow/parquet repos . Maybe there is a better mirror we can use. Or download directly from a URL. Nothing wrong with this PR, it's only explicitly doing `yum update` instead of implicitly via `yum install`, so I don't think we need to revert that change.

**Comment by jlefevre** [comment]
More repo shenanigans - just failed again.  We will need to look into this further.
```
...
http://dl.iad2.fedoraproject.org/pub/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: dl.iad2.fedoraproject.org; Unknown error"
The command '/bin/sh -c yum update -y &&     yum install -y https://apache.bintray.com/arrow/centos/7/apache-arrow-release-latest.rpm &&     yum install -y       re2-devel       arrow-devel       parquet-devel &&     yum clean all' returned a non-zero code: 1
ERROR: Step 'build-rook-img' failed ('1') !
The command "popper run" exited with 1.
```

The job is [here](https://travis-ci.com/github/uccross/skyhookdm-ceph-cls/builds/171186837), but I'm restarting the build log so may be overwritten.  But the raw log is [here](https://travis-ci.com/github/uccross/skyhookdm-ceph-cls/builds/171186837) if that remains, and I saved it.

**Comment by jlefevre** [comment]
created issue #48

**Pull request merged**
